name: Pull Request
run-name: Run Pull Request checks initiated by ${{ github.actor }} from ${{ github.head_ref }} to ${{ github.base_ref }}

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify_release_notes:
    name: Verify RELEASE_NOTES.md has been changed on ${{ github.base_ref }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Verify RELEASE_NOTES.md has been changed on ${{ github.base_ref }}
        if: github.base_ref == 'main'
        uses: tj-actions/verify-changed-files@v13
        id: verify_release_notes
        with:
          files: |
            RELEASE_NOTES.md

      - name: Abort If RELEASE_NOTES.md has not been changed on ${{ github.base_ref }}
        if: github.base_ref == 'main' && steps.verify_release_notes.outputs.files_changed != 'true'
        run: exit 1

      - name: Success
        run: exit 0

  test_pull_request:
    name: Run Unit Tests on ${{ github.ref }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore lib/AutoBackend.Sdk

      - name: Build
        run: dotnet build lib/AutoBackend.Sdk --configuration Release --no-restore

      - name: Test
        run: dotnet test lib/AutoBackend.Sdk --no-restore --verbosity normal
