name: Pull Request
run-name: Run Pull Request checks initiated by ${{ github.actor }} from ${{ github.head_ref }} to ${{ github.base_ref }}

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore lib/AutoBackend.Sdk

      - name: Build
        run: dotnet build lib/AutoBackend.Sdk --configuration Release --no-restore

      - name: Test
        run: dotnet test lib/AutoBackend.Sdk --no-restore --verbosity normal
